managed to make cevbreaker works on 2b2tpvp
IUDevman/gamesense-client pull request #268
Opened 2021-04-03 23:16 UTC by TechAle

2021-04-04 02:12 UTC, OlDestiny commented
# Penis 

Penis

2021-04-05 21:56 UTC, IUDevman requested changes
cleanup

2021-04-05 23:00 UTC, TechAle commented
Ya i will do it now

2021-04-06 01:39 UTC, TechAle commented
conflicts? Uh?

2021-04-06 03:06 UTC, IUDevman approved these changes

2021-04-06 03:06 UTC, merged